name: Matrix

on:
  workflow_dispatch:

jobs:
  run-matrix:
    strategy:
      matrix:
        os: ["arc-runner-set"]
        version: [1, 2, 3]
    runs-on: ${{ matrix.os }}
    steps:
      - name: simple
        run: |
          echo "Hello from: ${{ matrix.version }}"
